spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/picpay_clone
    username: rote
    password:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  api:
    versao: 1.0.0
  jpa:
    show-sql: true
    database: postgresql
    format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update